project:
  type: website
  output-dir: docs
  preview:
    port: 4200

language: 
  search-text-placeholder: Search

website:
  favicon: imgs/favicon.png
  back-to-top-navigation: true
  navbar:
    title: false
    logo: imgs/web-logo.png
    logo-alt: "Comsavvy logo"
    background: primary
    foreground: light
    pinned: true
    
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: News
        href: news.qmd
      - text: Credentials
        menu:
          - skills.qmd
          - text: Certifications
            href: certifications.qmd
          - text: Projects
            href: projects.qmd
          - text: CV
            href: cv/index.qmd

    tools:
      - icon: twitter
        href: https://www.x.com/comsavvy_ogp
        text: Comsavvy Twitter
      - icon: linkedin
        href: https://www.linkedin.com/in/comsavvy
        text: Comsavvy Linkedin
      - icon: github
        href: https://www.github.com/comsavvy
        text: Comsavvy GitHub
  
  search: 
    location: navbar
    type: textbox
    copy-button: true
      
  page-footer: 
    left: "© Olusola Ogundepo" 
    right: "Lagos, Nigeria"
    center: "Built with [![Quarto](https://quarto.org/quarto.png){width=70px height=18px style='margin-bottom: 3px;'}](https://quarto.org/)"

format:
  html:
    link-external-icon: true
    link-external-newwindow: true
    smooth-scroll: true
    
    theme: 
      light: [cosmo]
      dark: [cosmo, custom_dark.scss]
    css: style.css
    page-layout: full
