project:
  type: website
  output-dir: outputs

language: 
  search-text-placeholder: Search

website:
  favicon: imgs/favicon.png
  back-to-top-navigation: true
  navbar:
    title: false
    logo: imgs/web-logo.png
    logo-alt: "Comsavvy logo"
    background: primary
    foreground: light
    pinned: true
    
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: News
        href: news.qmd
      - text: CV
        href: cv/index.qmd
      - text: Projects
        href: projects.qmd

    tools:
      - icon: twitter
        href: https://www.x.com/comsavvy_ogp
      - icon: linkedin
        href: https://www.linkedin.com/in/comsavvy
      - icon: github
        href: https://www.github.com/comsavvy
      - icon: envelope
        href: "mailto::olusolaogundepo"
      - icon: box-arrow-in-right
        menu:
        - text: Certifications
          href: certifications.qmd
        - skills.qmd
  
  search: 
    location: navbar
    type: textbox
    copy-button: true
      
  page-footer: 
    left: "© Olusola Ogundepo" 
    right: "Website Created with [Quarto](https://quarto.org/)"

format:
  html:
    theme: 
      light: [cosmo]
      dark: [cosmo, custom_dark.scss]
    css: style.css
