project:
  type: website
  output-dir: outputs

website:
  title: "**COMSAVVY**"
  favicon: imgs/fav_icon.jpg
  back-to-top-navigation: true
  navbar:
    background: primary
    foreground: light
    pinned: true
    
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: CV
        href: cv/index.qmd
  
    tools:
      - icon: twitter
        href: https://www.x.com/comsavvy_ogp
      - icon: linkedin
        href: https://www.linkedin.com/in/comsavvy
      - icon: facebook
        href: https://www.facebook.com/comsavvy
      - icon: github
        href: https://www.github.com/comsavvy
      - icon: box-arrow-in-right
        menu:
        - text: Certifications
          href: certifications.qmd
        - skills.qmd
      
  page-footer: 
    left: "© Olusola Ogundepo" 
    center: "[COMSAVVY](about.qmd)"
    right: "Website Created with [Quarto](https://quarto.org/)"

format:
  html:
    theme: 
      light: [cosmo, custom_light.scss]
      dark: [cosmo, custom_dark.scss]
