project:
  type: website
  output-dir: outputs

website:
  title: "**COMSAVVY**"
  favicon: imgs/fav_icon.jpg
  back-to-top-navigation: true
  navbar:
    background: primary
    foreground: light
    pinned: true
    logo: imgs/comsavvy_logo_new.jpg
    
    left:
      - text: Home
        href: index.qmd
      - text: About
        href: about.qmd
      - text: Certifications
        href: certifications.qmd
      - skills.qmd
  
    tools:
      - icon: x
        href: https://www.x.com/comsavvy_ogp
      - icon: linkedin
        href: https://www.linkedin.com/in/comsavvy
      - icon: facebook
        href: https://www.facebook.com/comsavvy
      - icon: github
        href: https://www.github.com/comsavvy
      
  page-footer: 
    left: "© CC-By Olusola Ogundepo" 
    center: "[COMSAVVY](./about.qmd)"
    right: "Website Created with [Quarto](https://quarto.org/)"

format:
  html:
    theme: 
      light: cosmo
      dark: [cosmo, custom.scss]
    # css: styles.css

